In [1]:
import pandas as pd
import numpy as np
import ast

In [2]:
file = pd.read_csv("author.csv")

In [3]:
file.drop('Unnamed: 0',axis=1,inplace=True)
file.head()

,j_user,RT_l10,sd_RT,FC_l10,sd_FC,FC,RT
0,"{'id': 2107671, 'id_str': '2107671', 'name': '...",0.4,0.489898,1.7,3.796051,0.0,0.0
1,"{'id': 4869021, 'id_str': '4869021', 'name': '...",8.4,16.805951,76.1,127.668673,25.0,3.0
2,"{'id': 14206520, 'id_str': '14206520', 'name':...",0.2,0.400000,2.5,3.442383,0.0,0.0
3,"{'id': 22317044, 'id_str': '22317044', 'name':...",0.0,0.000000,0.3,0.458258,0.0,0.0
4,"{'id': 22935720, 'id_str': '22935720', 'name':...",3.6,6.711185,2.8,5.015974,0.0,1.0

In [4]:
file['j_user'][0] ### aquesta es la info que se'ns proporciona de cada usuari
#coses importants pel num de likes (de moment)(tambe les escullo perque son numeriques):
#protected
#followers_count
#friends_count
#listed_count (contains the number of public lists that this user is a member of.)
#favourites_count
#statuses_count

#afegeixo noves:
#geo_enabled
#verified
#contributors_enabled
#is_translator
#is_translation_enabled
#profile_background_tile
#profile_use_background_image
#has_extended_profile
#default_profile
#default_profile_image

"{'id': 2107671, 'id_str': '2107671', 'name': 'Gabriel Navarro', 'screen_name': 'gabinavarros', 'location': 'Murcia, Spain', 'description': '#Comunicación #Digital #Pymes. Licenciado en #Economía (@EconomicasUMU) y Graduado en #Filosofía (@FacFilosoMurcia) por la @UMU.', 'url': 'https://t.co/hWz3N9kxZM', 'entities': {'url': {'urls': [{'url': 'https://t.co/hWz3N9kxZM', 'expanded_url': 'http://about.me/gabinavarro', 'display_url': 'about.me/gabinavarro', 'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 5386, 'friends_count': 3861, 'listed_count': 304, 'created_at': 'Sat Mar 24 14:28:53 +0000 2007', 'favourites_count': 15325, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True, 'verified': False, 'statuses_count': 85493, 'lang': 'es', 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'FFFFFF', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme13/bg.gif', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme13/bg.gif', 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1059181678755831808/CDqXOZGB_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1059181678755831808/CDqXOZGB_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2107671/1540285952', 'profile_link_color': '0084B4', 'profile_sidebar_border_color': 'BDDCAD', 'profile_sidebar_fill_color': 'DDFFCD', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'}"

In [5]:
numl = len(file.index.values) #1592

cols_num = ['followers_count','friends_count','listed_count','favourites_count','statuses_count']
cols_TF = ['protected','geo_enabled','verified','contributors_enabled','is_translator','is_translation_enabled',
        'profile_background_tile','profile_use_background_image','has_extended_profile','default_profile',
        'is_translator','is_translation_enabled','default_profile_image']

for col in np.r_[cols_num,cols_TF]:
    file[col]=np.zeros(numl)

for line in range(numl):
    file['j_user'][line] =ast.literal_eval(file['j_user'][line])
    for col in cols_num:
        file[col][line] = int(file['j_user'][line][col])
    for col in cols_TF:
        if (file['j_user'][line][col]=='True'):
            file[col][line] = 1
        else:
            file[col][line] = 0

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [6]:
file.drop('j_user',axis=1,inplace=True)
file.head()

,RT_l10,sd_RT,FC_l10,sd_FC,FC,RT,followers_count,friends_count,listed_count,favourites_count,...,geo_enabled,verified,contributors_enabled,is_translator,is_translation_enabled,profile_background_tile,profile_use_background_image,has_extended_profile,default_profile,default_profile_image
0,0.4,0.489898,1.7,3.796051,0.0,0.0,5386.0,3861.0,304.0,15325.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,8.4,16.805951,76.1,127.668673,25.0,3.0,24075.0,100.0,96.0,20991.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.2,0.400000,2.5,3.442383,0.0,0.0,297.0,190.0,9.0,6257.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.000000,0.3,0.458258,0.0,0.0,557.0,650.0,19.0,6218.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3.6,6.711185,2.8,5.015974,0.0,1.0,54626.0,4640.0,1646.0,405.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
file.to_csv('clean_newauthors.csv')